# Generated by Django 6.0.5 on 2026-05-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='room',
            field=models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('bathroom', 'Bathroom'), ('kitchen', 'Kitchen'), ('exterior', 'Exterior')], default='exterior', max_length=50),
        ),
    ]
