# Generated by Django 6.0.5 on 2026-05-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_listingimage_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingimage',
            old_name='room',
            new_name='room_type',
        ),
    ]
